name: 'Tox Env'
description: 'Executes tox with a specific tox environment'
inputs:
  tox_env:  # id of input
    description: 'Tox environment that will be used'
    required: true
    default: ''
outputs:
  success_flag: # output will be available to future steps
    description: 'Whether tox succeeded'
runs:
  using: 'node12'
  main: 'dist/index.js'
